assemblee_nationale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('comptes/', include('comptes.urls')),
    path('forums/', include('forums.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/urls.py
from django.urls import path
from . import views

app_name = "forums"

urlpatterns = [
    path("", views.home, name="home"),
    path("detail/<slug>/", views.detail, name="detail"),
    path("posts/<slug>/", views.posts, name="posts"),
    path("latest_posts", views.latest_posts, name="latest_posts"),
    path("search", views.search_result, name="search_result"),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('articles/<str:pk>', views.articles, name='articles'),
    path('article-details/<str:id>', views.article_details, name='article-details'),
    path('actualite-video-details/<str:id>', views.actualite_video_details, name='actualite-video-details'),
    path('actualite-image-details/<str:id>', views.actualite_image_details, name='actualite-image-details'),
    path('act/', views.actualite, name="act"),
    path('galerie/<str:id>', views.galerie, name='galerie'),
    path('President/', views.President, name='President'),
    path('Mmbr/', views.Membre, name='Membre'),
    path('contact1/', views.contact1, name='contact1'),
    path('calendrier/', views.calendrierS, name='calendrierS'),
    path('Liste/', views.Liste_des_Lois, name='Liste_de_loi'),
    path('Evenement_H/', views.Evenement_H, name='Evenement_H'),
    path('searchEvenements/', views.searchEvenements, name='searchEvenements'),
    path('Travaux/', views.Travaux_en, name='Travaux'),
    path('Liste_depute/', views.Liste_des_depute_Fon, name='Liste_depute'),
    path('Ancien/', views.Ancien_President, name='Ancien'),
    path('Liste_d/', views.Liste_des_depute_P, name='Liste_d'),
    path('Annonce/', views.annonce, name='Annonce'),
    path('actualites/', views.actualite, name='Actualite'),
    path('Galerie_p/', views.Galerie_p, name='Galerie_p'),
    path('Symbole/', views.Symbole, name='Symbole'),
    path('Vac/', views.Vac, name='Vac'),
    path('Membre_Detail/', views.membredetail, name='MembreDetail'),
    path('Evenement_detail/<str:pk>', views.evenement_detail, name='Evenement_detail'),
    path('Histoire/', views.histoire, name='histoire'),
    path('Membre_Detail/<str:pk>', views.membredetail, name='MembreDetail'),
]

   

forums/models.py
from django.db import models
from tinymce.models import HTMLField
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from django.shortcuts import reverse
from comptes.models import Depute
from django.utils.text import slugify

class Category(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(Depute, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    description = HTMLField()

    class Meta:
        verbose_name_plural = "categories"
    def __str__(self):
        return f"{self.title} crée par {self.user.first_name} {self.user.last_name}"
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("forums:posts", kwargs={
            "slug":self.slug
        })

    @property
    def num_posts(self):
        return Post.objects.filter(categories=self).count()
    
    @property
    def last_post(self):
        return Post.objects.filter(categories=self).latest("date")

# class Topic(models.Model):
#     content = models.CharField(max_length=200)
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     user = models.ForeignKey(Depute, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.content

class Reply(models.Model):
    user = models.ForeignKey(Depute, on_delete=models.CASCADE)
    content = HTMLField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:100]

    class Meta:
        verbose_name_plural = "replies"

class Comment(models.Model):
    user = models.ForeignKey(Depute, on_delete=models.CASCADE)
    content = HTMLField()
    date = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)

    def __str__(self):
        return self.content[:100]
    

class Post(models.Model):
    title = models.CharField(max_length=400)
    content = HTMLField()
    # topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    parent_post = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(Depute, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category)
    approved = models.BooleanField(default=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )
    tags = TaggableManager()
    comments = models.ManyToManyField(Comment, blank=True)
    closed = models.BooleanField(default=False)
    state = models.CharField(max_length=40, default="zero")

    def __str__(self):
        return f"{self.title}, posté par {self.user.username}"
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
        
    @property
    def num_comments(self):
        return self.comments.count()
    

    @property
    def last_reply(self):
        return self.comments.latest("date")
        
    def get_url(self):
        return reverse("forums:detail", kwargs={
            "slug":self.slug
        })

    

forums/forms.py
from django import forms
from .models import Post, Category

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "categories", "tags"]
        
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class' : "form-control"
                })
            

class ForumForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["title", "description"]
        
    def __init__(self, *args, **kwargs):
        super(ForumForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class' : "form-control"
                })

forums/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Category, Post, Comment, Reply
from .utils import update_views
from .forms import PostForm, ForumForm
from django.contrib.auth.decorators import login_required
from comptes.models import Depute
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages



@login_required
def home(request):
    if request.user.identifiant == "":
        return redirect("loginDepute")
    
    form = ForumForm()
    if request.method == "POST":
        form = ForumForm(request.POST)
        if form.is_valid():
            author = request.user
            new_forum = form.save(commit=False)
            new_forum.user = author
            new_forum.save()
            form.save_m2m()
            return redirect("forums:home")
        
    forums = Category.objects.all()
    num_posts = Post.objects.all().count()
    num_users = Depute.objects.all().count()
    num_categories = forums.count()
    num_comments = Post.objects.all().count()
    try:
        last_post = Post.objects.latest("date")
    except:
        last_post = []
        
        
    context = {
        "forums":forums,
        "num_posts":num_posts,
        "num_comments":num_comments,
        "num_users":num_users,
        "num_categories":num_categories,
        "last_post":last_post,
        "title": "Forum de l'assemblee nationale",
        "form": form
    }
    return render(request, "forums/forums_list.html", context)


@login_required
def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    author = request.user
    author.num_post = Post.objects.filter(user=author).count()
    reponses = None
    
    if "comment-form" in request.POST:
        comment = request.POST.get("comment")
        if comment == "":
            messages.error(request, "Le commentaire ne doit pas être vide !")
        else:
            new_comment, _ = Comment.objects.get_or_create(user=author, content=comment)
            post.comments.add(new_comment.id)

    if "reply-form" in request.POST:
        reply = request.POST.get("reply")
        if reply == "":
            messages.error(request, "La reponse ne doit pas etre vide !")
        else:
            commenr_id = request.POST.get("comment-id")
            comment_obj = Comment.objects.get(id=commenr_id)
            new_reply, _ = Reply.objects.get_or_create(user=author, content=reply)
            comment_obj.replies.add(new_reply.id)

    comments = post.comments.all().order_by('-date')
    
    context = {
        "post":post,
        "comments": comments,
        "title": "Assemblee Nationale: "+post.title,
        'reponses': reponses
    }
    
    update_views(request, post)

    return render(request, "forums/details_forum.html", context)


def posts(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(approved=True, categories=category)
    paginator = Paginator(posts, 5)
    page = request.GET.get("page")
    form = PostForm(request.POST or None)
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) 

    if request.method == "POST":
        if form.is_valid():
            author = request.user
            new_post = form.save(commit=False)
            new_post.user = author
            new_post.save()
            form.save_m2m()
            return redirect(request.path)
        
    context = {
        "posts":posts,
        "forum": category,
        "form": form,
        "title": "L'Assemblee Nationale: Posts"
    }

    return render(request, "forums/posts.html", context)



def latest_posts(request):
    posts = Post.objects.all().filter(approved=True)[:10]
    context = {
        "posts":posts,
        "title": "L'Assemblee Nationale: Latest 10 Posts"
    }

    return render(request, "forums/latest-posts.html", context)


def search_result(request):
    return render(request, "forums/search.html")

forums/templates/forums/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'forums/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <!--NavBar Section-->
        <div class="navbar">
            <nav class="navigation hide" id="navigation">
                <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'forums:home' %}">Home</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}">Logout</a></li>
                    <li class="nav-item">{{user.first_name}}</li>
                </ul>
            </nav>
            <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
            <div class="brand">OZONE</div>
            {% if user.is_authenticated %}
            <div style="font-size:50px;font-weight300px;margin-left:100px;"><a href="{% url 'forums:create_post' %}">+</a></div>
            {% endif %}
        </div>
        <!--SearchBox Section-->
                <form action="{% url 'forums:search_result' %}" role="form" method="GET">
                <div class="search-box">
                    <div>
                        <select name="search-box" id="">
                            <option value="Everything">Everything</option>
                            <option value="Titles">Titles</option>
                            <option value="Descriptions">Descriptions</option>
                        </select>
                        <input type="text" name="q" placeholder="search ...">
                        <button type="submit" name="search"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                </form>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div style="background-color:#fff;color:#000;font-weight:bolder;padding:20px;width:100%;"> {{message}} </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <div style="margin-bottom: 150px;"></div>
    <footer>
        <span>&copy;  Elwil Reyes Hernandez | All Rights Reserved</span>
    </footer>
    <script src="{% static 'forums/js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

forums/templates/forums/create_post.html
{% extends 'forums/base.html' %}
{% block content %}

<h1 style="text-align:center; margin-block:50px; color:red;">Hey {{user}}, Write something</h1>

<form method="POST" style="margin-left:150px;">
    {% csrf_token %}    
    {{form}}
    <input type="submit" value="Save"  style="margin-block:50px;">
</form>

{% endblock content %}

forums/templates/forums/details_forum.html
{% extends 'web/base.html' %}
{% load hitcount_tags %}
{% block title %}Details du post{% endblock title %}

{% block content %}

<h2 style="text-align: center;">Sujet : </h2>

<h4 style="text-align: center;">{{post.title}}</h4>

<br>
<div class="mt-4">
    <div class="main-body p-0">
    <div class="inner-wrapper container">
    
    <div class="inner-main-body p-2 p-sm-3 collapse forum-content show mt-n5 col-12" style="overflow: scroll;height: 600px;">
      <div class="card mb-2">
        <div class="card-body">
          <div class="media forum-item">
            <a href="javascript:void(0)" class="card-link">
              <img src="{{post.user.photo.url}}" class="rounded-circle" width="50" alt="User" />
              <small class="text-muted ml-2">{{reply.user.categorie}}</small>
            </a>
            <div class="media-body ml-3">
              <a href="javascript:void(0)" class="text-secondary">{{post.user.first_name|title}}</a>
              <h5 class="mt-1">{{post.title}}</h5>
              <div class="mt-3 font-size-sm">
                <p>
                  {{post.content|safe}}
                </p>
              </div>
            </div>
            <div class="text-muted small text-center">
              <span class="d-none d-sm-inline-block"><i class="far fa-eye"></i>{% get_hit_count for post %} vues</span>
              <span><i class="far fa-comment ml-2"></i> {{post.num_comments}} commentaires</span>
            </div>
          </div>
        </div>
      </div>

      {% for comment in comments %}
      <div class="card mb-2">
        <div class="card-body">
          <div class="media forum-item">
            <a href="javascript:void(0)" class="card-link">
              <img src="{{comment.user.photo.url}}" class="rounded-circle" width="50" alt="User" />
              <small class="text-muted ml-2">{{reply.user.categorie}}</small>
            </a>
            <div class="media-body ml-3">
              <a href="javascript:void(0)" class="text-secondary">{{comment.user.first_name|title}}</a>
              <div class="mt-3 font-size-sm">
                <p>{{comment.content|safe}}</p>
                <p>{{comment.date}}</p>
              </div>
              
              <button onclick="showReplies('comment{{comment.id}}')" id="btnReply" class="btn btn-success">
                Repondre
              </button>

            </div>
          </div>
        </div>

        <!--Reply Area-->
      </div>
      <form action="." method="post">
        {% csrf_token %}
        <div id="comment{{comment.id}}" class="hide">
            <textarea class="form-control" name="reply" id="" placeholder="repondre ici ... "></textarea>
            <input type="submit" value="poster" style="margin-top: 10px;margin-bottom: 10px;" class="btn btn-info" name="reply-form">
            <input type="hidden" name="comment-id" value="{{comment.id}}">
        </div>

      </form>

  <!--Reply section-->
  {% for reply in comment.replies.all %}
  <div style="width: 95%; margin-left:5%;" class="card mb-2">
      <div class="card-body">
        <div class="media forum-item">
            <a href="javascript:void(0)" class="card-link">
              <img src="{{reply.user.photo.url}}" class="rounded-circle" width="50" alt="User" />
              <small class="text-muted ml-2">{{reply.user.categorie}}</small>
            </a>
            <div class="media-body ml-3">
              <a href="javascript:void(0)" class="text-secondary">{{post.user.first_name|title}}</a>
              
              <div class="mt-3 font-size-sm">
                <p>
                  {{reply.content|safe}}
                </p>
                <p>
                  {{reply.date}}
                </p>
              </div>
            </div>
          </div>
      </div>
  </div>
{% endfor %}      
    


    {% endfor %}
  </div>
    
    <div class="modal fade" id="threadModal" tabindex="-1" role="dialog" aria-labelledby="threadModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            
            <form method="POST" action=".">
                <div class="modal-header d-flex align-items-center bg-primary text-white">
                    <h6 class="modal-title mb-0 text-center text-light" id="threadModalLabel">Commentaire</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">X</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    {% csrf_token %} 
                    <div class="form-group">
                          <textarea name="comment" class="form-control" id="" placeholder="commenter ici ... "></textarea>
                    </div> 
                </div> 
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Annuler</button>
                    <input type="submit" class="btn btn-success" value="Poster" name="comment-form">
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    </div>

    <center>
    <button type="submit" data-toggle="modal" data-target="#threadModal" class="btn btnTheme fwMedium text-capitalize position-relative border-0 p-0 mt-5 mb-5" data-hover="Commenter" id="button">
        <span class="d-block btnText">Commenter</span>
    </button>
  </center>
{% endblock content %}

forums/templates/forums/forums_list.html
{% extends 'web/base.html' %}

{% block title %}Forums{% endblock title %}

{% block content %}
<h3 style="text-align: center;margin: 30px;">Bienvenue au Forum privé des membres de l'Assemblée Nationale </h3>
<h4 style="text-align: center;margin: 30px;">Voici les forums qui ont été crée </h4>
<div class="container">
    <div class="row mt-5">
        {% for forum in forums %}
            <div class="col-12 mb-3">
            <div class="card row-hover pos-relative py-3 px-3 mb-3 border-primary border-top-0 border-right-0 border-bottom-0 rounded-0">
                <div class="row align-items-center">
                    <div class="col-md-6 mb-3 mb-sm-0">
                        <h5>
                        <a href="{{forum.get_url}}" class="text-primary">{{forum.title}}</a>
                        </h5>
                        <p class="text-sm">
                            {{forum.description|safe}}
                        </p>
                        <div class="text-sm op-5">
                        </div>
                    </div>
                    
                    <div class="col-md-2 op-7">
                        <div class="row text-center op-7">
                            <div class="col px-1">
                                <i class="ion-connection-bars icon-1x"></i>
                                <span class="d-block text-sm">{{forum.num_posts}} Sujets</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 op-7">
                            {% if forum.last_post %}
                                <b><a href="#">Dernier post</a></b> par <a href="#">{{forum.last_post.user.first_name|title}}</a> 
                                <br>le <small>{{forum.last_post.date|date}}</small>
                            {% else %}
                                <span>Pas de post pour cette categorie</span>
                            {% endif %}
                    </div>
                    
                    </div>
                </div>
            </div>

            {% empty %}
                <div class="subforum-title">
                    <h1><i class="fa fa-frown-o"></i>&nbsp;Vous n'avez pas encore de thème de forum.</h1>
                </div>
            {% endfor %}

            <div class="container mt-5 col-12" style="display: block;width: 30%;">
                <center>
                    <form action="{% url 'forums:home' %}" method="POST">
                        {% csrf_token %} 
                        <div class="form-group">
                            {% for field in form %}
                            <label for="{{field.label}}">{{field.label}}</label>
                            {{field}}
                            {%for error in field.errors %}
                            <span style="color: red;">{{error}}</span><br />
                            {%endfor%}
                            {% endfor %}
                            <button type="submit" class="btn btnTheme fwMedium text-capitalize position-relative border-0 p-0 mt-5" data-hover="Créer" id="button">
                                <span class="d-block btnText">Créer</span>
                            </button>
                        </div>
                    </form>
                </center>
            </div>

            <div class="col-lg-3 mb-4 mb-lg-0 px-lg-0 mt-lg-0">
                <div style="visibility: hidden; display: none; width: 285px; height: 801px; margin: 0px; float: none; position: static; inset: 85px auto auto;"></div>

            <div data-settings="{&quot;parent&quot;:&quot;#content&quot;,&quot;mind&quot;:&quot;#header&quot;,&quot;top&quot;:10,&quot;breakpoint&quot;:992}" data-toggle="sticky" class="sticky" style="top: 85px;">    
                <div class="sticky-inner">
                    
                    <div data-settings="{&quot;parent&quot;:&quot;#content&quot;,&quot;mind&quot;:&quot;#header&quot;,&quot;top&quot;:10,&quot;breakpoint&quot;:992}" data-toggle="sticky" class="sticky" style="top: 85px;">
                        <div class="sticky-inner">
                            <div class="bg-white text-sm">
                                <h4 class="px-3 py-4 op-5 m-0 roboto-bold">Statistiques</h4>
                                <hr class="my-0">
                                <div class="row text-center d-flex flex-row op-7 mx-0">
                                <div class="col-sm-6 flex-ew text-center py-3 border-bottom border-right">
                                    <a class="d-block lead font-weight-bold" href="#">{{num_posts}}</a> Topics
                                </div>
                                <div class="col-sm-6 col flex-ew text-center py-3 border-bottom mx-0">
                                    <a class="d-block lead font-weight-bold" href="#">{{num_comments}}</a> Posts
                                </div>
                                <div class="col-sm-6 col flex-ew text-center py-3 border-bottom mx-0">
                                    <a class="d-block lead font-weight-bold" href="#">{{num_users}}</a> Membres
                                </div>
                                <div class="col-sm-6 col flex-ew text-center py-3 border-bottom mx-0">
                                    <a class="d-block lead font-weight-bold" href="#">{{num_categories}}</a> Categories
                                </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
</body>
</html>

forums/templates/forums/index.html
{% extends 'web/base.html' %}
{% block title %}Forum{% endblock title %}

{% block content %}
<h1>Forum</h1>
{% endblock content %}

forums/templates/forums/latest-posts.html
{% extends 'forums/base.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span>Les 10 derniers Posts</span>
        </div>
        <!--Display posts table-->
        <div class="posts-table">
            <div class="table-head">
                <div class="status">Status</div>
                <div class="subjects">Sujets</div>
                <div class="replies">Reponses/Vues</div>
                <div class="last-reply">Derniere Reponse</div>
            </div>

            {% for post in posts %}
            <div class="table-row">
                <div class="status"><i class="fa fa-fire"></i></div>
                <div class="subjects">
                    <a href="{{post.get_url}}">{{post.title}}</a>
                    <br>
                    <span>Lancé par <b><a href="">{{post.user.first_name|title}}</a></b> .</span>
                </div>
                <div class="replies">
                    {{post.num_comments}} commentaires <br> {% get_hit_count for post %} vues
                </div>

                <div class="last-reply">
                    {{post.last_reply.date|date}}
                    <br>Par <b><a href="">{{post.last_reply.user.first_name|title}}</a></b>
                </div>
            </div>
            {% endfor %}

            
            
        </div>

    {% endblock content %}

forums/templates/forums/search.html
{% extends 'forums/base.html' %}
{% load hitcount_tags %}
{% block content %}
    <div class="container">
        <!--Navigation-->
        <div class="navigate">
            <span>Recherche: {{query}} --> {{objects|length}} Resultat(s) Trouvé(s)</span>
        </div>
        <!--Display posts table-->
        <div class="posts-table">
            <div class="table-head">
                <div class="status">Status</div>
                <div class="subjects">Sujets</div>
                <div class="replies">Reponses/Vues</div>
                <div class="last-reply">Derniere Reponse</div>
            </div>

            {% for post in objects %}
            <div class="table-row">
                <div class="status"><i class="fa fa-fire"></i></div>
                <div class="subjects">
                    <a href="{{post.get_url}}">{{post.title}}</a>
                    <br>
                    <span>:Lqncé par <b><a href="">{{post.user.first_name|title}}</a></b> .</span>
                </div>
                <div class="replies">
                    {{post.num_comments}} commentaires <br> {% get_hit_count for post %} vues
                </div>

                {% if post.last_reply %}
                <div class="last-reply">
                    {{post.last_reply.date|date}}
                    <br>Par <b><a href="">{{post.last_reply.user.first_name|title}}</a></b>
                </div>
                {% else %}
                <div class="last-reply">
                    {{post.date|date}}
                    <br>Par <b><a href="">{{post.user.first_name|title}}</a></b>
                </div>
                {% endif %}
            </div>
            {% endfor %}

            
            
        </div>
        <!--Pagination starts-->
            {% if objects.is_paginated %}
            <div class="pagination">
                pages: {% for num_page in posts.paginator.page_range %} <a href="?page={{num_page}}">{{num_page}}</a> {% endfor %}
            </div>
            {% endif %}
        <!--pagination ends-->
    </div>

    {% endblock content %}