assemblee_nationale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('comptes/', include('comptes.urls')),
    path('forums/', include('forums.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('articles/<str:pk>', views.articles, name='articles'),
    path('article-details/<str:id>', views.article_details, name='article-details'),
    path('actualite-video-details/<str:id>', views.actualite_video_details, name='actualite-video-details'),
    path('actualite-image-details/<str:id>', views.actualite_image_details, name='actualite-image-details'),
    path('act/', views.actualite, name="act"),
    path('galerie/<str:id>', views.galerie, name='galerie'),
    path('President/', views.President, name='President'),
    path('Mmbr/', views.Membre, name='Membre'),
    path('contact1/', views.contact1, name='contact1'),
    path('calendrier/', views.calendrierS, name='calendrierS'),
    path('Liste/', views.Liste_des_Lois, name='Liste_de_loi'),
    path('Evenement_H/', views.Evenement_H, name='Evenement_H'),
    path('searchEvenements/', views.searchEvenements, name='searchEvenements'),
    path('Travaux/', views.Travaux_en, name='Travaux'),
    path('Liste_depute/', views.Liste_des_depute_Fon, name='Liste_depute'),
    path('Ancien/', views.Ancien_President, name='Ancien'),
    path('Liste_d/', views.Liste_des_depute_P, name='Liste_d'),
    path('Annonce/', views.annonce, name='Annonce'),
    path('actualites/', views.actualite, name='Actualite'),
    path('Galerie_p/', views.Galerie_p, name='Galerie_p'),
    path('Symbole/', views.Symbole, name='Symbole'),
    path('Vac/', views.Vac, name='Vac'),
    path('Membre_Detail/', views.membredetail, name='MembreDetail'),
    path('Evenement_detail/<str:pk>', views.evenement_detail, name='Evenement_detail'),
    path('Histoire/', views.histoire, name='histoire'),
    path('Membre_Detail/<str:pk>', views.membredetail, name='MembreDetail'),
]

   

web/templates/web/Calendrier_des_session.html
{% extends 'web/base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(http://placehold.it/1920x300);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Calendrier des Sessions</h1>
                    
                </div>
            </div>
        </div>
    </header>
    <article class="ItemfullBlock portfolioSingle bodyFontAlter pt-7 pb-7 pt-md-10 pb-md-9 pt-lg-14 pb-lg-13 pt-xl-22 pb-xl-19">
        <h3>Pas de donnees pour l'instant</h3>
    </article>
</main>

{% endblock content %}

web/templates/web/Contact1.html
{% extends 'web/base.html' %}

{% block title %} Contact 1 {% endblock title %}

{% block content %}

<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(http://placehold.it/1920x300);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Conatct</h1>
                    
                </div>
            </div>
        </div>
    </header>
    <div class="contactSectionWrap pt-7 pb-2 pt-md-10 pb-md-1 pt-lg-16 pb-lg-10 pt-xl-21 pb-xl-16">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-xl-5 mb-6">
                    <div class="pr-lg-10 pr-xl-20">
                        <header class="mb-8">
                            <h2 class="fwSemiBold h2Medium mb-4">Get In Touch</h2>
                            <p>We really appreciate you taking the time to get in touch. Please fill in the form below.</p>
                        </header>
                        <h4 class="fwSemiBold mb-3">Assemblee-Nationale</h4>
                        <ul class="list-unstyled contactInfoList mb-6">
                            <li>
                                <i class="fas fa-map-marker-alt icn position-absolute"><span class="sr-only">icon</span></i>
                                <strong class="text-lDark title">Addresse: </strong>345 Park Avenue, San Jose, CA 95110
                            </li>
                            <li>
                                <i class="fas fa-phone-alt icn position-absolute"><span class="sr-only">icon</span></i>
                                <strong class="text-lDark title">Numéro: </strong>1-800-7878-09
                            </li>
                            <li>
                                <i class="fas fa-envelope icn position-absolute"><span class="sr-only">icon</span></i>
                                <strong class="text-lDark title">Mail: </strong>egovt@example.com
                            </li>
                        </ul>
                        <h4 class="fwSemiBold mb-3">Heure D'ouverture</h4>
                        <strong class="font-weight-normal d-block">Du lundi au vendredi de 8h à 18h.</strong>
                        <ul class="list-unstyled socialNetworks saSocialNetworks d-flex flex-wrap p-0 mb-0 mt-7">
                            <li>
                                <a href="javascript:void(0);" class="facebook"style="background-color: green;">
                                    <i class="fab fa-facebook-square" aria-hidden="true" ><span class="sr-only">facebook</span></i>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="twitter" style="background-color:yellow;">
                                    <i class="fab fa-twitter" aria-hidden="true"><span class="sr-only">twitter</span></i>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="pinterest" style="background-color: #BB0505;">
                                    <i class="fab fa-pinterest" aria-hidden="true"><span class="sr-only">pinterest</span></i>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-7">
                    <div class="widget bg-white shadow contactFormWidget ml-xl-n5 mb-7 mb-md-5">
                        <div class="pt-8 pb-10 px-4 px-md-6 px-xl-8">
                            <h2 class="fwSemiBold h3Medium mb-4">Laissez votre message</h2>
                            <form action="{% url 'web:contact1' %}" method="POST" class="commentForm">
                                {% csrf_token %}
                                <div class="row mx-n2">
                                    <div class="col-12 col-sm-6 col-md-12 col-lg-6 px-2">
                                        <div class="form-group">
                                            <input type="text" name="nom" required class="form-control d-block w-100" placeholder="Nom">
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-6 col-md-12 col-lg-6 px-2">
                                        <div class="form-group">
                                            <input type="email" name="email" required class="form-control d-block w-100" placeholder="Email">
                                        </div>
                                    </div>
                                    <div class="col-12 px-2">
                                        <div class="form-group">
                                            <input type="text"name="sujet" required class="form-control d-block w-100" placeholder="Sujet">
                                        </div>
                                    </div>
                                    <div class="col-12 px-2">
                                        <div class="form-group">
                                            <textarea required name="message" class="form-control w-100 d-block" placeholder="Ecrivez votre message&hellip;"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <!-- <button type="button" class="btn btnTheme d-flex font-weight-bold text-capitalize position-relative border-0 p-0 mt-2 btnWidthSmall" data-hover="Envoyez">
                                    <span class="d-block btnText" style="background-color: #BB0505;">Envoyer le Message</span>
                                </button> -->
                                <input type="submit" name="contact" class="btn btnTheme d-flex font-weight-bold text-capitalize position-relative border-0 p-0 mt-2 btnWidthSmall p-2" style="background-color: green;color: antiquewhite;"  value="Envoyer le Message" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

web/templates/web/Evenement_a_lhemicycle.html
{% extends 'web/base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}

<main>
    <header class="pageMainHead d-flex position-relative w-100 text-white" style="background-image: url(/static/web/images/BannerDeputes.jpg);" style="position: absolute;left: -50%;">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Evènements à L'hemicycle</h1>
                    
                </div>
            </div>
        </div>
    </header>
    <section class="ItemfullBlock pt-7 pb-7 pt-md-10 pb-md-9 pt-lg-14 pb-lg-13 pt-xl-22 pb-xl-19">
        <div class="container">
            <header class="ifbFilterHead bg-light px-4 pt-4 pb-3 px-lg-8 pt-lg-7 pb-lg-6">
                <form action="{% url 'web:searchEvenements' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row mx-n3 d-flex justify-content-center">
                        <div class="formCol px-3">
                            <div class="form-group">
                                <label class="d-block fwMedium fontAlter text-lDark mb-2">Start Date</label>
                                <input type="date" name="dateDebut" class="form-control inputHeightMedium inputBdrTransparent d-block w- shadow">
                            </div>
                        </div>
                        <div class="formCol px-3">
                            <div class="form-group">
                                <label class="d-block fwMedium fontAlter text-lDark mb-2">End Date</label>
                                <input type="date" name="dateFin" class="form-control inputHeightMedium inputBdrTransparent d-block w- shadow">
                            </div>
                        </div>
                        <button type="submit" class="btn btnTheme ml-lg-3 w-50 mt-4 mt-lg-0 position-relative border-0 p-0" data-hover="Rechercher">
                            <span class="d-block btnText">Rechercher</span>
                        </button>
                    </div>
                </form>
            </header>

            <div class="row justify-content-center pt-8 pt-lg-11 pt-xl-14">
                {% for evenement in events %}
                <div class="col-12 col-md-6 col-lg-4 d-flex">
                    <article class="ueEveColumn position-relative shadow bg-white mb-6 mb-xl-12 w-100">
                        <div class="imgHolder position-relative">
                            <a href="javascript:void(0);">
                                <img src="{{evenement.image.url}}" class="img-fluid d-block w-100" alt="image {{evenement.nom}}">
                            </a>
                            <time class="ueTimeTag position-absolute text-center d-flex bg-white fontAlter fwSemiBold text-lDark text-uppercase" datetime="2011-01-12">
                                <span class="d-block text-white textDay flex-shrink-0 font-weight-bold">{{evenement.date|date:"j"}}</span>
                                <span class="d-block py-2 px-3">{{evenement.date|date:"F Y"}}</span>
                            </time>
                        </div>
                        <div class="ueDescriptionWrap pt-5 pb-8 px-5">
                            <strong class="d-block ueCatTitle fwSemiBold text-secondary mb-2">{{evenement.nom}}</strong>
                            <h3 class="h3Small fwMedium mb-3">
                                <a href="eventSingle.html">{{evenement.content|safe|truncatechars:15}}</a>
                            </h3>
                            <address>
                                <ul class="list-unstyled ueScheduleList">
                                    <li>
                                        <i class="icomoon-clock icn position-absolute"><span class="sr-only">icon</span></i>
                                        {{evenement.heureDebut}} - {{evenement.heureFin}}
                                    </li>
                                    <li>
                                        <i class="icomoon-location icn position-absolute"><span class="sr-only">icon</span></i>
                                        {{evenement.lieu}}
                                    </li>
                                </ul>
                            </address>
                            <a href="{% url 'web:Evenement_detail' evenement.pk %}" class="btn btnCustomLightOutline bdrWidthAlter btn-sm text-capitalize position-relative border-0 p-0 mt-3 align-top" data-hover="More Details">
                                <span class="d-block btnText">Plus de details</span>
                            </a>
                        </div>
                    </article>
                </div>
                {% empty %}

                <h3 style="text-align: center;margin-top: 30px;">Pas d'évènements trouvés</h3>

                {% endfor %}

            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center pt-2">
                    {% if evenements.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ evenements.previous_page_number }}">Précédent</a>
                    </li>
                    {% endif %}
                
                    {% for page in evenements.paginator.page_range %}
                        {% if page == evenements.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page }}">{{ page }}<span class="sr-only">(current)</span></a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                
                    {% if evenements.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ evenements.next_page_number }}">Suivant <i class="fas fa-chevron-right icn"><span class="sr-only">icon</span></i></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
</main>
{% endblock content %}

web/templates/web/Liste_des_depute_desP.html
{% extends 'web/base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}

<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(/static/web/images/BannerDepute.jpg);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Liste Des Députés Des Précédentes Législatures</h1>
                    
                </div>
            </div>
        </div>
    </header>
    <section class="exploreDepartmentsBlock py-8 py-md-10 py-lg-14 py-xl-22">
        <div class="container">
            <div class="row justify-content-center isoContentHolder mb-8">
                
                {% for depute in deputes %}
                
                <div class="col-12 col-md-6 col-lg-4 isoCol culture">
                    <div class="echColumnClassic bg-white position-relative mb-6">
                        <div class="imgWrap">
                            <img src="{{depute.image.url}}" class="img-fluid" alt="image description">
                            <a href="{{depute.image.url}}" class="echCountTag position-absolute fwSemiBold text-white px-3 py-1 lightbox" data-fancybox="true">
                                <i class="far fa-image icn"><span class="sr-only">icon</span></i>
                                6
                            </a>
                        </div>
                        <div class="echcCaptionWrap px-3 py-2 px-sm-5 py-sm-4">
                            <h3 class="mb-0">
                                <strong class="d-block font-weight-normal fontBase echCatTitle mb-1">Culture</strong>
                                <a href="{% url 'web:MembreDetail' depute.pk %}">Plus de details</a>
                            </h3>
                        </div>
                    </div>
                </div>  
                {% empty %}
                <h3 style="text-align: center;">Pas de données pour l'instant</h3>
                {% endfor %}
            </div>
        </div>
    </section>
</main>

{% endblock content %}

web/templates/web/Symbole.html
{% extends 'web/base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}

<main>
    <header class="pageMainHead d-flex position-relative w-100 text-white" style="background-image: url(/static/web/images/emblemesBanner.jpg);">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Symbole De L'Assemblée Nationale</h1>
                    
                </div>
            </div>
        </div>
    </header>
    <article class="newsSingleWrap pt-7 pb-2 pt-md-9 pb-md-4 pt-lg-14 pb-lg-8 pt-xl-22 pb-xl-13">
        <h3>Pas de donnees pour l'instant</h3>
    </article>
</main>

{% endblock content %}

web/templates/web/actualite_image_details.html
{% extends 'web/base.html' %}

{% block title %}Details Actualité{% endblock title %}

{% block content %}
<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(http://placehold.it/1920x300);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Plus de détails de l'ctualité</h1>
                </div>
            </div>
        </div>
    </header>
    <article class="newsSingleWrap pt-7 pb-2 pt-md-9 pb-md-4 pt-lg-14 pb-lg-8 pt-xl-22 pb-xl-13">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 col-xl-9 mb-6">
                    <div class="pr-xl-14">
                        <div class="imgHolder mb-4 mb-md-8 position-relative">
                            <div class="nrcImageSlider">
                                {% for imageAssociee in imageAssociees %}
                                    <div>
                                        <div class="imgWrap">
                                            <img src="{{imageAssociee.source.url}}" class="img-fluid w-100" alt="image description">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <header class="nrcHead">
                            <strong class="d-block fwMedium title mb-1">
                                <i class="icnTheme fwMedium icomoon-clock"><span class="sr-only">icon</span></i>
                                <time datetime="2011-01-12">{{actualiteImage.created_at|date}}</time>
                            </strong>
                            <h2 class="h2vii fwSemiBold mb-5">{{actualiteImage.titre}}</h2>
                        </header>
                        <p>{{actualiteImage.description|safe}}</p>
                    </div>
                </div>
            </div>
        </div>
    </article>
</main>
{% endblock content %}

web/templates/web/article_details.html
{% extends 'web/base.html' %}

{% block title %}Details Article{% endblock title %}

{% block content %}
<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(http://placehold.it/1920x300);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">{{article.titre}} - {{article.categorie.nom}}</h1>
                </div>
            </div>
        </div>
    </header>
    <article class="dsSingleContent pt-7 pb-2 pt-md-10 pb-md-1 pt-lg-16 pb-lg-10 pt-xl-21 pb-xl-16">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 col-xl-9 order-lg-2 mb-6">
                    <div class="pl-xl-14">
                        <header class="fzMedium mb-9">
                            <h2 class="fwSemiBold h2vii">{{article.titre}}</h2>
                            <p>{{article.description|safe}}</p>
                        </header>
                        <div class="overflow-hidden mb-3 mb-lg-7">
                            <!-- <div class="dscInnerSliderWrap float-sm-right mb-7 mb-sm-0 mt-sm-2 ml-auto mr-auto mr-sm-0 ml-sm-6">
                                <div class="dcsInnSlider">
                                    <div>
                                        <div class="dcsisImageHolder">
                                            <img src="http://placehold.it/435x355" class="img-fluid w-100" alt="image description">
                                        </div>
                                    </div>
                                    <div>
                                        <div class="dcsisImageHolder">
                                            <img src="http://placehold.it/435x355" class="img-fluid w-100" alt="image description">
                                        </div>
                                    </div>
                                </div>
                            </div> -->
                            <p>{{article.description|safe}}</p>
                        </div>
                        <div class="accordion ctAccordion" id="ctdepartsAccordion">
                            <div class="ctaccRow mb-4">
                                <div class="ctaccOpener">
                                    <a class="fontAlter fwMedium" href="#ctr1" data-toggle="collapse" aria-expanded="false" aria-controls="ctr1">Eco-Friendly equipments and materials</a>
                                </div>
                                <div class="collapse ctaccSlide" id="ctr1" data-parent="#ctdepartsAccordion">
                                    <div class="overflow-hidden px-5 pb-1">
                                        <p>One of the most common additions people make to their cars in order to keep the heat out is a windshield visor. Cars become warm in the summer because direct sunlight enters in through the windows. This is why we park in the shade whenever we can. Since the largest windshield.In fact, wind is becoming cheap enough in many places in the U.S. and around the world to compete effectively with fossil fuels.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="ctaccRow mb-4">
                                <div class="ctaccOpener">
                                    <a class="fontAlter fwMedium" href="#ctr2" data-toggle="collapse" aria-expanded="true" aria-controls="ctr2">Eco-Friendly equipments and materials</a>
                                </div>
                                <div class="collapse show ctaccSlide" id="ctr2" data-parent="#ctdepartsAccordion">
                                    <div class="overflow-hidden px-5 pb-1">
                                        <p>One of the most common additions people make to their cars in order to keep the heat out is a windshield visor. Cars become warm in the summer because direct sunlight enters in through the windows. This is why we park in the shade whenever we can. Since the largest windshield.In fact, wind is becoming cheap enough in many places in the U.S. and around the world to compete effectively with fossil fuels.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="ctaccRow mb-4">
                                <div class="ctaccOpener">
                                    <a class="fontAlter fwMedium" href="#ctr3" data-toggle="collapse" aria-expanded="false" aria-controls="ctr3">Award winning design management</a>
                                </div>
                                <div class="collapse ctaccSlide" id="ctr3" data-parent="#ctdepartsAccordion">
                                    <div class="overflow-hidden px-5 pb-1">
                                        <p>One of the most common additions people make to their cars in order to keep the heat out is a windshield visor. Cars become warm in the summer because direct sunlight enters in through the windows. This is why we park in the shade whenever we can. Since the largest windshield.In fact, wind is becoming cheap enough in many places in the U.S. and around the world to compete effectively with fossil fuels.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4 col-xl-3 order-lg-1 mb-6">
                    <aside class="dscSidebar pt-1 mr-xl-n5">
                        <nav class="widget mb-6 mb-lg-10 widgetDepartsNav widgetBgLight py-5 px-6">
                            <h3 class="fwSemiBold mb-4">
                                <a href="javascript:void(0);" class="btnDcsBack align-middle mr-1"><i class="fas fa-chevron-left"><span class="sr-only">icon</span></i></a>
                                Les autres articles
                            </h3>
                            <ul class="list-unstyled pl-0 mx-n2 mb-0 mb-3">
                                {% for post in articles %}
                                    {% if post.pk != article.pk %}
                                    <li>
                                        <a href="{% url 'web:article-details' post.pk %}">{{post.titre}}</a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                        
                    </aside>
                </div>
            </div>
        </div>
    </article>
</main>
{% endblock content %}

web/templates/web/articles.html
{% extends 'web/base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
<main>
    <header class="pageMainHead d-flex position-relative bgCover w-100 text-white" style="background-image: url(http://placehold.it/1920x300);">
        <div class="alignHolder d-flex w-100 align-items-center">
            <div class="align w-100 position-relative">
                <div class="container">
                    <h1 class="text-white mb-2">Les articles</h1>
                </div>
            </div>
        </div>
    </header>
    <section class="ItemfullBlock pt-7 pb-7 pt-md-10 pb-md-9 pt-lg-14 pb-lg-13 pt-xl-22 pb-xl-19">
        <div class="container">
            <div class="pt-7 pb-6 pt-lg-11 pb-lg-9 pt-xl-14 pb-xl-12">
                
                {% for article in articles %}
                <article class="ueEveColumn__list position-relative px-4 py-3 px-lg-8 py-lg-6">
                    <div class="d-lg-flex align-items-md-center">
                        <div class="d-md-flex align-items-md-center flex-grow-1">
                            <div class="imgHolder rounded-circle overflow-hidden flex-shrink-0 mr-4 mr-lg-10 mb-1 mb-md-0">
                                <img src="{{article.image.url}}" class="img-fluid rounded-circle" alt="image description">
                            </div>
                            <div class="descrWrap flex-grow-1">
                                <!-- <strong class="tagTitle d-block text-secondary fwSemiBold mb-2">Entertainement</strong> -->
                                <h3 class="fwMedium">
                                    <a href="{% url 'web:article-details' article.pk %}">{{article.titre}}</a>
                                </h3>
                                <div class="list-unstyled ueScheduleList mb-0">
                                    <p>{{article.description|safe}}</p>
                                </div>
                            </div>
                            <a href="{% url 'web:article-details' article.pk %}" class="btn btnCustomLightOutline bdrWidthAlter btn-sm text-capitalize position-relative border-0 p-0 flex-shrink-0 ml-md-4" data-hover="Plus de Détails">
                                <span class="d-block btnText">Plus de Détails</span>
                            </a>
                        </div>
                    </div>
                </article>
                {% endfor %}
            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center pt-2">
                    <li class="page-item disabled">
                        <a class="page-link" href="javascript:void(0);">Prev</a>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="javascript:void(0);">1 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);">Next <i class="fas fa-chevron-right icn"><span class="sr-only">icon</span></i></a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</main>
{% endblock content %}